-- Create GPF_USR_DETAILS table
-- This table stores GPF user application details

CREATE TABLE GPF_USR_DETAILS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    APPL_AMT NUMBER NOT NULL,
    APPL_DATE DATE NOT NULL,
    ENCLOSERS CHAR(1),
    GPF_TYPE CHAR(1),
    HOUSE_ADDR VARCHAR2(200),
    PERSNO NUMBER NOT NULL,
    PURPOSE NUMBER NOT NULL
);

-- Add comments for documentation
COMMENT ON TABLE GPF_USR_DETAILS IS 'GPF User Application Details';
COMMENT ON COLUMN GPF_USR_DETAILS.ID IS 'Auto-generated primary key';
COMMENT ON COLUMN GPF_USR_DETAILS.APPL_AMT IS 'Application amount';
COMMENT ON COLUMN GPF_USR_DETAILS.APPL_DATE IS 'Application date';
COMMENT ON COLUMN GPF_USR_DETAILS.ENCLOSERS IS 'Enclosers flag (Y/N)';
COMMENT ON COLUMN GPF_USR_DETAILS.GPF_TYPE IS 'GPF type (F/E)';
COMMENT ON COLUMN GPF_USR_DETAILS.HOUSE_ADDR IS 'House address (optional)';
COMMENT ON COLUMN GPF_USR_DETAILS.PERSNO IS 'Personnel number';
COMMENT ON COLUMN GPF_USR_DETAILS.PURPOSE IS 'Purpose code (references GPF_PURPOSE_F or GPF_PURPOSE_E)';

-- Create indexes for better query performance
CREATE INDEX idx_gpf_usr_persno ON GPF_USR_DETAILS(PERSNO);
CREATE INDEX idx_gpf_usr_appl_date ON GPF_USR_DETAILS(APPL_DATE);
CREATE INDEX idx_gpf_usr_purpose ON GPF_USR_DETAILS(PURPOSE);

-- Insert sample data (optional - remove if not needed)
INSERT INTO GPF_USR_DETAILS (APPL_AMT, APPL_DATE, ENCLOSERS, GPF_TYPE, HOUSE_ADDR, PERSNO, PURPOSE) 
VALUES (50000, SYSDATE, 'Y', 'F', '123 Main Street, City', 1001, 1);

INSERT INTO GPF_USR_DETAILS (APPL_AMT, APPL_DATE, ENCLOSERS, GPF_TYPE, HOUSE_ADDR, PERSNO, PURPOSE) 
VALUES (25000, SYSDATE-30, 'N', 'E', NULL, 1002, 1);

INSERT INTO GPF_USR_DETAILS (APPL_AMT, APPL_DATE, ENCLOSERS, GPF_TYPE, HOUSE_ADDR, PERSNO, PURPOSE) 
VALUES (75000, SYSDATE-60, 'Y', 'F', '456 Oak Avenue, Town', 1003, 2);

COMMIT;
