-- V18: Create GPF_SUB_DETAILS table
CREATE TABLE GPF_SUB_DETAILS (
    ID            NUMBER         PRIMARY KEY,
    PERS_NUMBER   VARCHAR2(50)   NOT NULL,
    ADD_SUB_DATE  DATE           NOT NULL,
    GPF_SUB       NUMBER(15, 2)  NOT NULL,
    GPF_RET       NUMBER(15, 2)  NOT NULL
);

CREATE SEQUENCE GPF_SUB_DETAILS_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER GPF_SUB_DETAILS_TRG
BEFORE INSERT ON GPF_SUB_DETAILS
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT GPF_SUB_DETAILS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/
