-- Fix GPF_SUB_DETAILS trigger to not override ID when Hibernate provides it via sequence
CREATE OR REPLACE TRIGGER GPF_SUB_DETAILS_TRG
BEFORE INSERT ON GPF_SUB_DETAILS
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT GPF_SUB_DETAILS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/
