-- Create new table GPF_YEARS with 3 columns
-- Note: GPF table cleanup will be done in V9 migration
CREATE TABLE GPF_YEARS (
    PASS_NUMBER VARCHAR2(50) PRIMARY KEY,
    GPF_YEARS NUMBER(10, 2) NOT NULL,
    CLOSING_BALANCE NUMBER(15, 2) NOT NULL
);

-- Create index for better performance
CREATE INDEX idx_gpf_years_pass_number ON GPF_YEARS(PASS_NUMBER);

-- Insert sample data for testing
INSERT INTO GPF_YEARS (PASS_NUMBER, GPF_YEARS, CLOSING_BALANCE)
VALUES ('PASS001', 5.5, 125000.00);

INSERT INTO GPF_YEARS (PASS_NUMBER, GPF_YEARS, CLOSING_BALANCE)
VALUES ('PASS002', 10.0, 350000.00);

INSERT INTO GPF_YEARS (PASS_NUMBER, GPF_YEARS, CLOSING_BALANCE)
VALUES ('PASS003', 15.5, 750000.00);

COMMIT;
