-- Manual script to create GPF_PURPOSE_F and GPF_PURPOSE_E tables
-- Run this if Flyway migrations are not working
-- Connect as: sqlplus aditya/aditya2468@localhost:1521/xe

-- Create GPF_PURPOSE_F table
CREATE TABLE GPF_PURPOSE_F (
    CODE NUMBER NOT NULL,
    PURPOSE VARCHAR2(20),
    PERCENTAGE NUMBER,
    RULE VARCHAR2(20),
    CONSTRAINT pk_gpf_purpose_f PRIMARY KEY (CODE)
);

-- Add comments for GPF_PURPOSE_F
COMMENT ON TABLE GPF_PURPOSE_F IS 'GPF Purpose codes with rules and percentages';
COMMENT ON COLUMN GPF_PURPOSE_F.CODE IS 'Unique purpose code identifier';
COMMENT ON COLUMN GPF_PURPOSE_F.PURPOSE IS 'Purpose description (max 20 characters)';
COMMENT ON COLUMN GPF_PURPOSE_F.PERCENTAGE IS 'Percentage value associated with the purpose';
COMMENT ON COLUMN GPF_PURPOSE_F.RULE IS 'Rule description (max 20 characters)';

-- Insert sample data for GPF_PURPOSE_F
INSERT INTO GPF_PURPOSE_F (CODE, PURPOSE, PERCENTAGE, RULE) VALUES (1, 'House Construction', 90, 'Rule 1');
INSERT INTO GPF_PURPOSE_F (CODE, PURPOSE, PERCENTAGE, RULE) VALUES (2, 'Education', 50, 'Rule 2');
INSERT INTO GPF_PURPOSE_F (CODE, PURPOSE, PERCENTAGE, RULE) VALUES (3, 'Medical Emergency', 100, 'Rule 3');
INSERT INTO GPF_PURPOSE_F (CODE, PURPOSE, PERCENTAGE, RULE) VALUES (4, 'Marriage', 50, 'Rule 4');
INSERT INTO GPF_PURPOSE_F (CODE, PURPOSE, PERCENTAGE, RULE) VALUES (5, 'Other Purpose', 25, 'Rule 5');

-- Create GPF_PURPOSE_E table
CREATE TABLE GPF_PURPOSE_E (
    CODE NUMBER NOT NULL,
    PURPOSE VARCHAR2(20),
    PERCENTAGE NUMBER,
    RULE VARCHAR2(20),
    CONSTRAINT pk_gpf_purpose_e PRIMARY KEY (CODE)
);

-- Add comments for GPF_PURPOSE_E
COMMENT ON TABLE GPF_PURPOSE_E IS 'GPF Purpose codes (E category) with rules and percentages';
COMMENT ON COLUMN GPF_PURPOSE_E.CODE IS 'Unique purpose code identifier';
COMMENT ON COLUMN GPF_PURPOSE_E.PURPOSE IS 'Purpose description (max 20 characters)';
COMMENT ON COLUMN GPF_PURPOSE_E.PERCENTAGE IS 'Percentage value associated with the purpose';
COMMENT ON COLUMN GPF_PURPOSE_E.RULE IS 'Rule description (max 20 characters)';

-- Insert sample data for GPF_PURPOSE_E
INSERT INTO GPF_PURPOSE_E (CODE, PURPOSE, PERCENTAGE, RULE) VALUES (1, 'Emergency Medical', 100, 'Rule E1');
INSERT INTO GPF_PURPOSE_E (CODE, PURPOSE, PERCENTAGE, RULE) VALUES (2, 'Education Loan', 60, 'Rule E2');
INSERT INTO GPF_PURPOSE_E (CODE, PURPOSE, PERCENTAGE, RULE) VALUES (3, 'Home Repair', 75, 'Rule E3');
INSERT INTO GPF_PURPOSE_E (CODE, PURPOSE, PERCENTAGE, RULE) VALUES (4, 'Vehicle Repair', 40, 'Rule E4');
INSERT INTO GPF_PURPOSE_E (CODE, PURPOSE, PERCENTAGE, RULE) VALUES (5, 'Personal Loan', 30, 'Rule E5');

COMMIT;

-- Verify tables were created
SELECT 'GPF_PURPOSE_F' as TABLE_NAME, COUNT(*) as ROW_COUNT FROM GPF_PURPOSE_F
UNION ALL
SELECT 'GPF_PURPOSE_E' as TABLE_NAME, COUNT(*) as ROW_COUNT FROM GPF_PURPOSE_E;

-- Show all data
SELECT 'F' as CATEGORY, CODE, PURPOSE, PERCENTAGE, RULE FROM GPF_PURPOSE_F
UNION ALL
SELECT 'E' as CATEGORY, CODE, PURPOSE, PERCENTAGE, RULE FROM GPF_PURPOSE_E
ORDER BY CATEGORY, CODE;
